### ISSUE TITLE
Stand and Dismount broken in TBC client

### ISSUE THREAD

**Issue by alimbocl** [leatrix/leatrix-plus-bcc#10]
Stand and Dismount appears to be broken. I tried enabling and re-enabling it (with /rl) but still not working. This is on 2.5.32.

**Comment by leatrix** [comment]
It seems to be working fine for me.  I just initiated combat while mounted and it dismounted me.  I selected a flight point from the flight map and it dismounted me.

What exactly are you trying to do that's failing and how is it failing?  Which class are you logged in with (unshifting from forms isn't supported)?

It could be a problem with another addon.  Disable all other addons.  Does that fix it?

**Comment by NYPD** [comment]
Weird, I didn't see an option in the gui for this, also checked description on curse and the BCC Leatrix Plus didn't mention dismount so I thought it was a game limitation / bug.

However, I now restarted the game and now I see the option in game and it works for me... I wonder if the old leatrix plus folder (for vanilla classic) somehow interfered when installing the new one

**Comment by alimbocl** [comment]
Hey there. What I am normally used to is that if I am mounted and I try to use an ability (let's say Bloodthirst for example) it will auto-dismount/stand up. Using the latest version this seems to not work mounted or sitting. I tried disabling all my addons except LTP but same result.

I tried it on my priest with slightly different results. It seems like the stuff I have macro'd doesn't cause me to dismount (I mentioned Bloodthirst above - that is a macro with /startattack in it). When I use a simple spell like Powerword: Shield it dismounts me immediately (correctly). When I tried it with a macro it does not dismount me (a simple mouseover macro flash heal).

**Comment by alimbocl** [comment]
> 
> 
> Weird, I didn't see an option in the gui for this, also checked description on curse and the BCC Leatrix Plus didn't mention dismount so I thought it was a game limitation / bug.
> 
> However, I now restarted the game and now I see the option in game and it works for me... I wonder if the old leatrix plus folder (for vanilla classic) somehow interfered when installing the new one

I have a fresh version of LTP BCC. I deleted my addons folder entirely and got fresh BCC copies of addons.

**Comment by leatrix** [comment]
So it appears that in BCC, Stand and Dismount is no longer needed as the game has that functionality built-in now.  However, the game still doesn't dismount you when choosing a flight.  So the Stand and Dismount option will probably be changed to simply dismount you when choosing a flight and that's it.

**Comment by alimbocl** [comment]
Any advice for how to auto-dismount on the warrior? I've tried a bunch of abilities and if I don't have rage it won't dismount me.

**Comment by alimbocl** [comment]
> 
> 
> Not as it is. It could be added perhaps.

Feature request :)

**Comment by NYPD** [comment]
You could always make you abilities into a macro like I have done for my warrior:
```
#showtooltip Shield Slam
/dismount
/equip [noequipped:shields] Blessed Qiraji Bulwark
/cast Shield Slam
```

I've done a bunch of these for other abilities too (sunder, concussion blow, etc)

**Comment by alimbocl** [comment]
> 
> 
> You could always make you abilities into a macro like I have done for my warrior:
> 
> ```
> #showtooltip Shield Slam
> /dismount
> /equip [noequipped:shields] Blessed Qiraji Bulwark
> /cast Shield Slam
> ```
> 
> I've done a bunch of these for other abilities too (sunder, concussion blow, etc)

TY

**Comment by leatrix** [comment]
In 2.5.33.alpha.2, 'Stand and Dismount' is now 'Dismount automatically'.  The game will now stand and dismount your character for most occasions without addons.  So this option will now dismount your character when you select a flight location and when you attempt to cast a spell even if you have no rage/energy/mana/range to cast the spell.

Please let me know how you go on with it.

https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all

**Comment by NYPD** [comment]
Looks good. I updated to 2.5.33.alpha.3 and was able to get dismounted on my rogue trying to do sinister strike and on my warrior trying to mortal strike with no rage next to an enemy

This is by the way WITHOUT using the ```/dismount``` macro on skills

**Comment by alimbocl** [comment]
Is this in 2.5.33 or do I need the alpha release still?

**Comment by NYPD** [comment]
Should be in 2.5.33 based on the release notes
```
2.5.33 - 21st May 2021
- The 'Stand and dismount' option is now called 'Dismount automatically'.  Most of what it did before is now included in the game.  So now, the option will dismount you when you select a flight location or when you attempt to cast a spell regardless of whether you have enough resource to cast or whether the target is in range.
- Fixed an issue with 'Recent chat window' which caused a Lua error when attempting to show Battle.net messages.
- The 'Remove raid restrictions' option has been removed since it's not needed for Burning Crusade Classic.
```
