### ISSUE TITLE
minimap button interaction with itemrack sets

### ISSUE THREAD

**Issue by knasen88** [leatrix/leatrix-plus-bcc#100]
using mouse to select set in itemrack from the button bag they generally travel outside the confines of the window and makes it all close unless you're really quick about it. Maybe have it close on next mouseclick outside the window rather than a timer?

showcase
https://streamable.com/ifjpvc

**Comment by leatrix** [comment]
In 2.5.88.alpha.4, if you have 'Combine addon buttons' enabled and you are using ItemRack, the ItemRack minimap button frame will no longer close while the pointer is over it.
