### ISSUE TITLE
sound block request

### ISSUE THREAD

**Issue by chorp-cpu** [leatrix/leatrix-plus-bcc#102]
mage table
warlock healthstone table
mechanostrider
hunter bird pet screech (it goes off every second)

**Comment by leatrix** [comment]
Added a mechanostriders setting to 9.1.41.alpha.1.

**Comment by leatrix** [comment]
Added mechanostriders and Screech to the latest alphas for BCC and Classic Era/SoM.
https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all
https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/all
