### ISSUE TITLE
Ctrl+Clicking on a chat window causes Lua errors

### ISSUE THREAD

**Issue by silverhawke249** [leatrix/leatrix-plus-bcc#11]
I intended to pop out the window that lets you copy from the recent chat messages, but it gives me this Lua error instead:

```
Leatrix_Plus\Leatrix_Plus-2.5.32.lua:5554: attempt to index global 'C_BattleNet' (a nil value)
[string "@Leatrix_Plus\Leatrix_Plus-2.5.32.lua"]:5554: in function <Leatrix_Plus\Leatrix_Plus.lua:5528>
[string "@Leatrix_Plus\Leatrix_Plus-2.5.32.lua"]:5588: in function <Leatrix_Plus\Leatrix_Plus.lua:5586>
[string "=[C]"]: ?
```

I recall that the Alts addon also had a similar problem with the `C_BattleNet` functions actually not in that namespace (in fact, the namespace isn't defined in TBC Classic).

**Comment by leatrix** [comment]
Many thanks for the report.  Should be fixed in 2.5.33.alpha.3.
https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all
