### ISSUE TITLE
Error with leatrix plus on wrath classic (ptr)

### ISSUE THREAD

**Issue by telias82** [leatrix/leatrix-plus-bcc#115]
20x Leatrix_Plus\Leatrix_Plus-2.5.117.lua:6973: attempt to call method 'SetTexture' (a nil value)
[string "@Leatrix_Plus\Leatrix_Plus-2.5.117.lua"]:6973: in function `?'
[string "@Leatrix_Plus\Leatrix_Plus-2.5.117.lua"]:12013: in function <Leatrix_Plus\Leatrix_Plus.lua:11625>

Locals:
self = <table> {
 LeaPlusNav9 = <unnamed> {
 }
 BuffFrameX = -184.284561
 LockItem = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:77
 BuffFrameY = 0
 LeaPlusNav2.s = <unnamed> {
 }
 RecentChatSize = 170
 MakeFT = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:297
 TipCursorY = 0
 FlightBarY = -66
 MinimapR = "TOPRIGHT"
 TipCursorX = 0
 Page0 = <unnamed> {
 }
 DressupItemButtons = "On"
 DismountNoTaxi = "On"
 InviteFromWhisper = "On"
 grid = <unnamed> {
 }
 MuteYawns = "On"
 MakeCB = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:12554
 VanityAltLayout = "Off"
 BuffFrameScale = 1.400000
 LoadVarAnc = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:207
 AcceptPartyFriends = "On"
 LockOption = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:475
 WidgetX = 0
 FlightBarWidth = 230
 MakeSL = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:12500
 Page4 = <unnamed> {
 }
 ShowDropTip = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:243
 ReloadCheck = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:530
 NoPartyInvites = "Off"
 NumberOfPages = 9
 FlightBarA = "TOP"
 HideZoneText = "Off"
 EnhanceDressup = "Off"
 MoreFontSizes = "Off"
 SetDim = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:494
 HideFrames = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:389
 LeaPlusQuestFontSize = 12
 TipShowTarget = "On"
 FilterChatMessages = "Off"
 FocusR = "CENTER"
 ShowErrorsFlag = 1
 NoDuelRequests = "Off"
 CooldownsOnPlayer = "Off"
 QuestFontChange = "On"
 TipOffsetX = -13
 AutoQuestKeyMenuTable = <table> {
 }
 AutoRepairGuildFunds = "On"
 Page9 = <unnamed> {
 }
 ZygorToggle = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:309
 TipNoHealthBar = "Off"
 TooltipAnchorMenu = 1
 ShowRaidToggle = "Off"
 ShowVendorPrice = "Off"
 EnhanceProfessions = "Off"
 IsPlusShowing = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:404
 HideMiniMapButton = "On"
 LeaPlusNav5.s = <unnamed> {
 }
 MakePage = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:14414
 ShowWowheadLinks = "Off"
 HideMiniClock = "Off"
 AutoQuestCompleted = "On"
 Page7 = <unnamed> {
 }
 flightFrame = <unnamed> {
 }
 CfgBtn = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:275
 LeaPlusMailFontSize = 15
 WidgetR = "TOP"
 NoFriendRequests = "Off"
 AutoRepairShowSummary = "On"
 ShowBagSearchBox = "Off"
 MuteMechSteps = "On"
 NoCombatLogTab = "Off"
 muteTable = <table> {
 }
 ClassColorsInChat = "Off"
 MoveChatEditBoxToTop = "Off"
 ViewPortEnable = "Off"
 MinimapY = -2
 MakeWD = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:12491
 LeaPlusNav4 = <unnamed> {
 }
 ShowFlightTimes = "On"
 Page1 = <unnamed> {
 }
 ShowTooltip = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:259
 LeaPlusNav0 = <unnamed> {
 }
 MailFontChange = "On"
 LeaPlusNav3 = <unnamed> {
 }
 MinimapMod = "Off"
 MainPanelA = "BOTTOMRIGHT"
 HideActionButtonText = "Off"
 BuffFrameR = "TOPRIGHT"
 ShowTrainAllBtn = "On"
 AutoSellJunk = "On"
 AutoRepairGear = "Off"
 CreateDropDown = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:12718
 AutomateGossip = "On"
 LoadVarNum = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:197
 AutoQuestKeyMenu = 1
 LoadVarStr = <function> defined @Leatrix_Plus\Leatrix_Plus.lua:217
 HideDressupStats = "Off"
 RecentChatWindow = "Off"
 DismountShowFormBtn = "On"
 AutoReleaseNoAlterac = "Off"
 ShowCooldownID = "On"
 InviteFriendsOnly = "Off"
 LeaPlusNav6 = <unnamed> {
 }
 Page5 = <unnamed> {
 }
 HideMiniZoomBtns = "Off"
 ViewPortBottom = 0
 ManageFocus = "Off"
 ManageWidget = "Off"
 SetWeatherDensity = "On"
 ClassColPlayer = "On"
 ShowMinimapIcon = "Off"
 EasyItemDestroy = "Off"
 ViewPortTop = 0
 InvKey = "inv"
 NoGryphons = "On"
 FrmEnabled = "On"
 HideErrorMessages = "Off"
 Page3 = <unnamed> {
 }
 LeaStartPage = 7
 FriendlyGuild = "On"
 WidgetA = "TO

**Comment by leatrix** [comment]
Many thanks for reporting.  Should be fixed in 2.5.118.alpha.20 and later.
