### ISSUE TITLE
Wrong quest text position with Enhance quest log

### ISSUE THREAD

**Issue by GregoryGH** [leatrix/leatrix-plus-bcc#119]
If you enable Enhance quest log quest text is on wrong position.

BCC 2.5.119.alpha.19
![image](https://user-images.githubusercontent.com/9971731/184709262-dfe67d59-777a-4ac9-a311-292ddd9f543d.png)

**Comment by leatrix** [comment]
Thanks for your report and sorry about that.  Should be fixed in 2.5.119.alpha.20.

**Comment by GregoryGH** [comment]
Working now in alpha.21. Thanks a lot and no need to sorry!
