### ISSUE TITLE
Widget frame position

### ISSUE THREAD

**Issue by Mario-Beck** [leatrix/leatrix-plus-bcc#12]
Hello and thx for updating this Addon!

I have a little issue with the widget frame:
As soon as i activate the widget management the output appears in the center of the screen - now matter how i drag the green frame around.

Yes i use other addon, but no addon for moving frames around as far as I am aware.

See Screenshot:
![leatrix widget bug](https://user-images.githubusercontent.com/1230890/119097163-b4c73b00-ba14-11eb-8dda-d878600a5f22.jpg)

**Comment by leatrix** [comment]
Disable all other addons.  Is it fixed?

**Comment by imap86** [comment]
For me the problem got solved with deactivate Titan Panel.

**Comment by leatrix** [comment]
Thanks, impac86.  Specifically, it's the 'Disable screen adjust' setting in Titan Panel that causes it.  In LTP 2.5.38.alpha.1, the 'Manage widget' configuration panel will now show a warning and a fix me button if Titan Panel is preventing the widget frame from being saved correctly.
