### ISSUE TITLE
suggestion: new feature

### ISSUE THREAD

**Issue by amey1956** [leatrix/leatrix-plus-bcc#13]
during classic i used https://www.curseforge.com/wow/addons/vikinggraveyards

there have been many new graveyards added in the pre-patch with more to come with official expac release on 6/1

is this something that you would consider adding to ltp or maps - i'm not sure which one shows the dungeon locations but similar to that. 

thanks in advance for consideration ;)

**Comment by leatrix** [comment]
This has been added to the latest alpha releases for BCC and Wow Classic.  There is a new setting in 'Show points of interest' called 'Show spirit healers'.
https://github.com/leatrix/leatrix-maps-bcc/issues/22
