### ISSUE TITLE
Suggestion - Pressing up to scroll through your previously typed messages

### ISSUE THREAD

**Issue by Mrhgb** [leatrix/leatrix-plus-bcc#14]
I'm trying to steer away from ELVUI and your addon is incredible and replaces so many other addons, but there's one small thing I really miss from ELVUI, and that's when you press up and it'll bring up the last few things you typed. Hopefully, you can add this.

**Comment by leatrix** [comment]
While the chat editbox has focus (flashing insertion point), you can hold alt and press up/down arrow keys to cycle through previous chat messages.  Is this what you want?

**Comment by Mrhgb** [comment]
> While the chat editbox has focus (flashing insertion point), you can hold alt and press up/down arrow keys to cycle through previous chat messages. Is this what you want?

It is yes! I didn't know about holding alt. Thanks.
