### ISSUE TITLE
Edit Box Bug

### ISSUE THREAD

**Issue by ByzBlue** [leatrix/leatrix-plus-bcc#19]
If you have the edit box set to top of window, but your chat window is an irregular size, it overlaps the text.

![image](https://user-images.githubusercontent.com/54814665/121219994-3c54dc80-c852-11eb-8007-a3e13d07b740.png)

Also as a feature request, I'd like to suggest adding some of the chat options from Chatter, since it is no longer maintained: /tt, alt+click to invite, turning 'invite' or 'inv' into clickable links, timestamps, etc.

**Comment by leatrix** [comment]
The chat editbox placement is intentional.  Other suggestions appreciated.
