### ISSUE TITLE
When targeting enemy player's target or friendly players target, MAJOR Loss of FPS 100 to 20

### ISSUE THREAD

**Issue by Woolselv** [leatrix/leatrix-plus-bcc#20]
When I am out in the world (playing TBC Classic), and I have LP running, and I target someone else's target they are attacking, I lose about 80 FPS immediately, and everything bogs down.  If I clear the target, I shoot back to 100FPS.  I have narrowed it down to LP, as I cycled through all addons, and when its on it happens, when it is off, it does not.  Love LP, great work, hope there is a way to figure out what is causing this!

**Comment by leatrix** [comment]
Are you using 'Class icon portraits' ('Frames')?  If so, what happens when you disable that option?

**Comment by Woolselv** [comment]
That is 100% the issue.  Well done!  When disabled I do not experience the drops.  Thank you!  Hopefully you are able to figure out what causes that option to do that! :)

**Comment by leatrix** [comment]
The game (not LTP) refreshes the target of target frame constantly while it's showing.  After every refresh, LTP has to apply the class portrait texture to the frame.  This is what reduces the performance.

Just out of curiosity, please try 2.5.40.alpha.1 and let me know if there's any improvement.
https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all

Note that you must restart your game client after installing this update.

**Comment by Woolselv** [comment]
Unfortunately, still having the issue that I was having before, does still seem to have the same level of FPS degradation, so no marked improvement. Sorry to report that :(

**Comment by leatrix** [comment]
That's for the feedback.  I was just curious about that.  There's nothing that can be done other than remove the option entirely.  As the game refreshes the target of target frame constantly while it's showing, LTP has no other option than to constantly apply the class portrait texture.  That's what causes the FPS drop so it can't be avoided.

**Comment by leatrix** [comment]
So I'll keep the option in the addon but in 2.5.40.alpha.2, there is a note in the option tooltip advising on the possible framerate drop.  The option is incredibly useful and there have only been a few reports of the framerate drop.  It can't be avoided though.  If the framerate drop is a problem, just keep the option disabled.  There are other addons that show class portraits but they all work the same way.
https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all

**Comment by leatrix** [comment]
Also linking this here:
https://github.com/leatrix/leatrix-plus-bcc/issues/7

**Comment by leatrix** [comment]
Can you attach screenshots of your graphics settings (both the graphics settings and the advanced graphics settings)?

**Comment by Woolselv** [comment]
![WoWScrnShot_060921_100444](https://user-images.githubusercontent.com/85593294/121370011-5651f600-c90a-11eb-9f3a-589f64a07e4b.jpg)
![WoWScrnShot_060921_100447](https://user-images.githubusercontent.com/85593294/121370019-58b45000-c90a-11eb-84bd-9763e7307d33.jpg)

**Comment by leatrix** [comment]
Thanks for those.  This is really difficult to replicate for me.  I can see that the framerate drops sometimes when in a party group but it's so rare that I have trouble replicating it.  When the framerate drop happens, reloading the UI fixes it and it's fine again then I can't replicate it again.

The last time the framerate drop happened, I was in a party with one other player.  I was targeting the other player.  When the other player targeted me, my framerate was fine.  When they targeted themselves, my framerate dropped.  But after reloading my UI, my framerate was fine again and I couldn't replicate the framerate drop again.

**Comment by leatrix** [comment]
The 'Class icon portraits' option is removed in the latest alphas for all clients.  There are standalone addons that offer this feature if you need it but they all work the same way so will all reduce framerate.
