### ISSUE TITLE
suggestion: profession feature

### ISSUE THREAD

**Issue by Shulsfm** [leatrix/leatrix-plus-bcc#21]
Hi, request feature for profession window:
Search bar to filter profession patterns & recipes
Check box to only show recipes that you have the materials to make

example:
https://www.curseforge.com/wow/addons/classicprofessionfilter

**Comment by leatrix** [comment]
Suggestion appreciated.  Note that fixes have been added to the latest alpha release of Leatrix Plus to ensure compatibility with Classic Profession Filter.
https://github.com/leatrix/leatrix-plus-bcc/issues/25
