### ISSUE TITLE
MASSIVE FPS Drops

### ISSUE THREAD

**Issue by Eldrimoth** [leatrix/leatrix-plus-bcc#22]
Since the TBC update I've had to keep LP disabled. Every time I turn it on if I'm in a dungeon/raid or PvPing I get massive frame rate drops( Going from 100 to 5-10). As soon as I disable LP the issue no longer happens. I disabled most of my addons and still have the problem.

addons I left on for reference
Weak Aura's. Threat Plates. Details, Buff times, BigDebuffs and Omni CC/bar

Is there some type of debug move I can run it in to see how what could be causing this issue. I see some other comments about FPS drops here as well. 

Hope we can get this fixed as this was by far my favorite addon for classic wow and I wish to use it in TBC.

**Comment by leatrix** [comment]
Are you using 'Class icon portraits' ('Frames')?  If so, does disabling that help?

**Comment by Eldrimoth** [comment]
> Are you using 'Class icon portraits' ('Frames')? If so, does disabling that help?

Holy hell. That fixed it. Thank you so much!

**Comment by leatrix** [comment]
Thanks for letting me know.  I'll probably just remove that option entirely.

**Comment by leatrix** [comment]
The option is removed in 2.5.42.alpha.1.  There are standalone addons for this feature if you really need it but they all work the same way so will all cause framerate drops.
