### ISSUE TITLE
suggestion: guild rank in  tooltip

### ISSUE THREAD

**Issue by BirkenBoard** [leatrix/leatrix-plus-bcc#23]
would be nice to see guild rank on tooltip as well as guild. used in other addons for tooltips such as tiptac and tinytooltip but would eliminate the need for tooltip addons with this.

**Comment by leatrix** [comment]
In the 'Enhance tooltip' configuration panel, you can show guild ranks for characters in your own guild.

**Comment by BirkenBoard** [comment]
I saw that, closed it finding that, but showing ranks of other guilds would be nice, I know my member's ranks but seeing horde ranks and other guilds is really nice.

**Comment by Zwyk** [comment]
You can just line 6454 in Leatrix_Plus.lua to
`if true then`

This will show rank of players regardless if they're in the your guild. I'm doing that for about a year now, gotta change it each time you update LTP unless they add this option officially! No idea why it's not yet :(

**Comment by leatrix** [comment]
In 2.5.42.alpha.5, there's a new setting that let's you see ranks for players in other guilds.  It's disabled by default.  This setting is also in the latest alpha releases for Wow Classic and Shadowlands.
https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all
