### ISSUE TITLE
Expanded profession view, the numbers are covered up

### ISSUE THREAD

**Issue by kevsboomba** [leatrix/leatrix-plus-bcc#25]
As I am still leveling my professions, I use the expanded view of those panes. But the level, such as 358/375 is partially covered up by the blue bar showing progress and I cannot read it. I love this feature, but cant use it while leveling a profession as you know the skill ups and learning recipes is important!

**Comment by leatrix** [comment]
Have a screenshot?

**Comment by 1shka** [comment]
Same issue but only when using other addon (ClassicProfessionFilter) https://imgur.com/a/nKCVZXV
Without it everything is good https://imgur.com/a/y0Vbk9o

**Comment by leatrix** [comment]
Thanks for the feedback, 1shka.
The compatibility issue with Classic Profession Filter is fixed in LTP 2.5.42.alpha.4 for BCC.
https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all

It's also fixed in LTP 1.13.110.alpha.3 for Wow Classic.

**Comment by leatrix** [comment]
Closing this as I'm assuming the problem was Classic Profession Filter (for which compatibility fixes have been added to both BCC and Wow Classic releases).

**Comment by kevsboomba** [comment]
Yes, it was. and thank you!!!
