### ISSUE TITLE
suggestion: expand personal macros

### ISSUE THREAD

**Issue by vyrnius** [leatrix/leatrix-plus-bcc#26]
Hej!

First I want to thank you for your hard work! Leatrix is such an incredible and awesome tool! 
I want to make a suggestion and since I can't comment on your leatrix page and bc there are already 2 suggestions here, I will go on and try it
Could you add the function to expand the possible amount of personal macros? atm it is locked to 18 macros per character and that's just not enough
I am sure a lot of people don't like to have their mage and paladin macro in the same spot (for example)

man... I really need this function ^^

thank you for your time! :-)

**Comment by leatrix** [comment]
Suggestion and praise appreciated.
