### ISSUE TITLE
How do i remove or vastly enlarge rogue combo point frame (track poisons, kidney shot, etc) & target health bar

### ISSUE THREAD

**Issue by MerkuriTBC** [leatrix/leatrix-plus-bcc#28]
No option that I could find, but maybe it's there somewhere.  perfect addon other than this problem that i seem to not be able to find the option to solve.  any help is appreciated!

**Comment by leatrix** [comment]
You can use 'Manage frames' ('Frames') to enlarge the entire player and target frames (which would include player resource bars such as combo points) but that's all.
