### ISSUE TITLE
Disable bag automation does not work

### ISSUE THREAD

**Issue by metaluks** [leatrix/leatrix-plus-bcc#29]
If the disable bag automation option is enabled, my bags should stay open when interacting with a merchant or the mail box.

Expected behaviour: My bags stay open/ closed when interacting with a merchant, the bank or the mail box.

Actual behaviour: My bags still open/close on every interaction with a merchant, the bank or the mail box.

BCC 2.5.41

**Comment by leatrix** [comment]
Disable other addons.  Does it work?

**Comment by metaluks** [comment]
It works with disabled addons. Sorry for not checking properly.

**Comment by leatrix** [comment]
Enable your other addons gradually until you find the addon causing the problem.  If it's a bag replacement addon, you may find that it has its own setting to control bag automation.  If it doesn't and you want me to look at the conflict, let me know which addon it is.

**Comment by metaluks** [comment]
It's caused by the tukUI Addon, specifically the bag module. As soon as I activate it, the automation does not work any more. If there is any possibility to make them work together, I am all for it!

**Comment by leatrix** [comment]
Not possible.  When you open the bag module, Tukui replaces various Blizzard bag functions with its own functions - including the function that 'Disable bag automation' uses.  You should make a support ticket with Tukui and ask them to add an option to disable bag automation.
