### ISSUE TITLE
Please don't automate pickup of Return to Abyssal Shelf

### ISSUE THREAD

**Issue by d07RiV** [leatrix/leatrix-plus-bcc#3]
The quest is 100% useless and auto picking it up sends you on a long flight you can't interrupt. And since you need to talk to the quest NPC to return home, gotta remember to hold that shift.

**Comment by leatrix** [comment]
Thanks for the report.  In 2.5.13, quests from Wing Commander Brack and Gryphoneer Windbellow will no longer be selected or accepted automatically.

**Comment by d07RiV** [comment]
Thanks, there's probably going to be a fair number of these. The addon just picked Aldor for me before I realized what's going on :D

**Comment by leatrix** [comment]
In 2.5.14, quests from Khadgar (Allegiance to Aldor/Scryer, Shattrath) will not be accepted, selected or turned-in automatically and quests from Witch Doctor Mau'ari (E'Ko quests, Winterspring) will not be selected automatically.
