### ISSUE TITLE
Tooltip Anchor on Cursor

### ISSUE THREAD

**Issue by Kayla350** [leatrix/leatrix-plus-bcc#30]
Doesn't seem to be anchoring to the cursor from the Interface - Enchance Tooltip settings.

Stays in the same spot on the bottom right.

Version 2.5.41

**Comment by leatrix** [comment]
Anchor to cursor applies to the game world but not to the user interface.
If the tooltip for the game world is not anchored to the cursor, disable all other addons and test again.
