### ISSUE TITLE
Enhance tooltip - Pets and Neutral NPC blue too similar to Mages blue (?)

### ISSUE THREAD

**Issue by boktai1000** [leatrix/leatrix-plus-bcc#34]
Just giving some feedback here / opinion after testing it out. By the way I love the feature, I have it enabled now and it's pretty great! No issues to report other than color opinions.

Some (but not all) NPCs and Pets report a "sanctuary" sort of blue for their color on the tooltip, which is very close to the Mage blue. I'm wondering if there's a better default/NPC/Pet related color that could be used?

Feel free to close this as I'm not really sure if it's a "bug" or anything more than a thought / take I wanted to bring up.

Here are some examples-

Mage:

![image](https://user-images.githubusercontent.com/9054563/122262305-e5c35000-ce9a-11eb-8383-59147724243b.png)

Pet:

![image](https://user-images.githubusercontent.com/9054563/122262340-efe54e80-ce9a-11eb-8932-0b87140bcca7.png)

NPC (Hemet Nesingwary):

![image](https://user-images.githubusercontent.com/9054563/122262375-f7a4f300-ce9a-11eb-8845-9091184e3ad8.png)

How he appears in-game:

![image](https://user-images.githubusercontent.com/9054563/122262422-025f8800-ce9b-11eb-850d-b0c26c5fa11a.png)

**Comment by leatrix** [comment]
Yes, I know.  It's just been that way for 10 years now (yes, Leatrix Plus has been around for 10 years!) so people are used to it.  If you want to suggest a [different color](https://www.w3schools.com/colors/colors_hexadecimal.asp), by all means do so.  The blue color that you're referring to is color code 00aaff.

**Comment by boktai1000** [comment]
Appreciate the information! And apologies on the catch-up if I'm going through the same cycles that were done 10+ years ago :)

Is Leatrix Plus pulling the color from the game itself natively, like is that color associated with those mob types or is it something that you decided/was hardcoded in?

The only suggestion I have, well, is personal and it seems like it's entirely personal on what someone may expect or what for these values.

But if I had to pick, I would suggest matching the tooltip with the mob's hostility value - like in this case just green as is reflected in the nameplate for the character. It's sort of what I expected to be the case. As far as Hunter pets go, I think the same hostility value could be applied there, or maybe even just made "Hunter Green" to match their associated Hex Code. Probably one of those options so it isn't blue and out of place if other things changed.

Anyways, that's just my $0.02 after giving it some though. Apologies for the learning lesson here - but appreciate you taking the feedback at least for consideration. Thanks for the great addon and keep it up

**Comment by leatrix** [comment]
The blue color ([00AAFF](https://www.w3schools.com/colors/colors_picker.asp?colorhex=00AAFF)) is from AFTooltip, an ancient addon that I used in vanilla Wow.  AFTooltip used the color for friendly (non-flagged) NPCs.  I really liked it so I used it in Leatrix Plus.  The mage class color in BCC is actually [3FC7EB](https://www.w3schools.com/colors/colors_picker.asp?colorhex=3FC7EB) which is a slightly different shade of blue.

**Comment by boktai1000** [comment]
I've become accustom to this at this point and love the throwback. Thanks for letting me know, and consider this as you tagged it just some initial knee-jerk feedback/thoughts on it.

Thanks again for the great addon - going to close this out.
