### ISSUE TITLE
Missing/Wrong texture on chat after installed others addons

### ISSUE THREAD

**Issue by ziin** [leatrix/leatrix-plus-bcc#35]
![image](https://user-images.githubusercontent.com/35908124/122471356-30bd9000-cf8d-11eb-9945-ad78dcba328f.png)
![image](https://user-images.githubusercontent.com/35908124/122471408-43d06000-cf8d-11eb-9e5f-e50923fea72f.png)

After install and uninstall ElvUI, my chat became weird without the texture that it has before.
Any idea on how to fix this without compromise my entire interface?

**Comment by leatrix** [comment]
Is the problem that the chat tabs are missing?
Disable all other addons.  Does that fix it?

**Comment by ziin** [comment]
> Is the problem that the chat tabs are missing?
> Disable all other addons. Does that fix it?

No. I was refering the glow that flickers when there are new messages below. I think it had a cool look before I tried ElvUi. Now I only see this blue retangle.

**Comment by leatrix** [comment]
The blue rectangle is Leatrix Plus option 'Hide chat buttons'.
