### ISSUE TITLE
Missing Class icon portraits option

### ISSUE THREAD

**Issue by Rectomus** [leatrix/leatrix-plus-bcc#36]
Missing Class icon portraits (Show class icons in the portrait frames)  since June 17th update.
Only have the class colored frames option now.
Did disable all other addons but still no class icon portraits.
![Capture](https://user-images.githubusercontent.com/86082339/122476000-7aa97480-cf93-11eb-854c-ae46435fb746.PNG)

**Comment by leatrix** [comment]
https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/3353940

**Comment by Rectomus** [comment]
ok thank you for answering
