### ISSUE TITLE
Feature request: Options to hide some elements while in combat and the background of the bars

### ISSUE THREAD

**Issue by giulianisanches** [leatrix/leatrix-plus-bcc#40]
Hi,

This is not an usual feature request as i want to check out the code and implement it myself.

The thing is: Lua and Addon Development is not something i know and need to learn a few things here and there.

Before start to code, i want to know if there is interest to have the following features in Leatrix Plus:

- Hide background/texture from action bars ( as leatrix does with griphons )
- Hide chat in combat
- Hide minimap in combat
- Hide bars in combat (here i will be albe to choose the bars). This case is special as i usually have the right bars in my monitor for trivial things, not used in any context considering combat.

Thanks in advance.

**Comment by leatrix** [comment]
Feedback appreciated.
