### ISSUE TITLE
Auto-accept Battlegrounds Queue  - Is a must add !!  Pls upvote if u agree 

### ISSUE THREAD

**Issue by Shadowdemonz** [leatrix/leatrix-plus-bcc#41]
Wouldn't it be nice to be able to auto accept a battle grounds queue while u need to afk for a fast bio  or ur tabbed out. It would be a great addtiontion to this already amazing app. Pls upvote this  if u agree.

**Comment by leatrix** [comment]
If you mean you want to accept the 'battleground is ready' prompt so that you can enter the battleground while afk, it's not possible.  Blizzard protected that section of code to stop people doing exactly that (for obvious reasons).
