### ISSUE TITLE
ClassicProfessionFilter SearchMats floats off CraftFrame

### ISSUE THREAD

**Issue by jpaolin** [leatrix/leatrix-plus-bcc#43]
LTP version `2.5.44.alpha.3`

SearchMats checkbox floats off the `CraftFrame` (Enchanting). Looks like the code was not copied there.
![SearchMats floats off CraftFrame](https://user-images.githubusercontent.com/5832046/123514241-ea88c080-d65f-11eb-89ca-2f10964f110b.png)

I'm having no issues with `TradeSkillFrame`

**Comment by leatrix** [comment]
Added to latest alpha release.

**Comment by jpaolin** [comment]
Confirmed, fixed in `2.5.44.alpha.4`. Thank you
