### ISSUE TITLE
"Unclamp chat frame" setting doesn't seem to work

### ISSUE THREAD

**Issue by Alex-Hughes-94** [leatrix/leatrix-plus-bcc#45]
I'm playing on TBC Classic, and trying to move my chat frame into the very bottom corner of the screen. I enabled the "Unclamp chat frame" setting on Leatrix Plus, but nothing happened. I can drag individual windows around, but the main chat box with the General tab won't move. I can resize it with easy resizing enabled, but not move it. I've tried disabling all other addons, and have clicked and dragged just about every part of the chatbox with every mouse button. If I'm just doing it wrong, there should maybe be a tooltip explaining how to move the frame once it's unclamped.

**Comment by leatrix** [comment]
Easy resizing only works if the chat frame is locked so... the chat frame must be locked.  Right-click the General chat tab and click Unlock.  Then you can drag the window.  If that doesn't work, disable all other addons and try again.
