### ISSUE TITLE
"LEATRIX PLUS: WRONG VERSION INSTALLED!"

### ISSUE THREAD

**Issue by holyloktar** [leatrix/leatrix-plus-bcc#47]
I just updated my addons and Leatrix stopped working. I disabled all addons and just enabled it and still get the same error.
![Leatrix Failed to Load 07-16-2021](https://user-images.githubusercontent.com/63972594/126026872-750c4989-e803-4390-9b97-ce5edf3af05b.jpg)

**Comment by leatrix** [comment]
You have the wrong version of Leatrix Plus installed.  You made this ticket on the BCC tracker so presumably you're running BCC which means you have tried to install Leatrix Plus for Shadowlands or Wow Classic on your BCC install.  Remove it and install [Leatrix Plus for BCC](https://www.curseforge.com/wow/addons/leatrix-plus-bcc).

If you use [CurseForge App](https://download.curseforge.com/), you shouldn't have this issue.

**Comment by holyloktar** [comment]
Actually, it was working fine until I logged in today. I am running the TBC version:

![image](https://user-images.githubusercontent.com/63972594/126027862-eba48aae-7be8-420f-aef3-f2ba0201ca35.png)

**Comment by holyloktar** [comment]
Looking at it again, Curse Forge still had both BCC and Classic installed. I removed them both, reinstalled BCC and it's now working. Not sure how it was working before, but it's all good now. Thanks!

**Comment by leatrix** [comment]
Just for some additional info and in case it helps anyone else reading this in future, the current game interface version for BCC is 20501.  You can see this in Wow by entering /ltp game.

On BCC, the error you saw will show up if Leatrix Plus sees that your game interface version is less than 20000 or more than 29999.  On Wow Classic and Shadowlands, there are similar checks to make sure you are running the correct version.
