### ISSUE TITLE
Marks of Sargeras are turned in one at a time

### ISSUE THREAD

**Issue by d07RiV** [leatrix/leatrix-plus-bcc#48]
As title says, addon always picks the single mark option, which makes it 10x slower.

On a side note, is there any reason why DoesQuestHaveRequirementsMet is checking quest title (requiring correct translations in localization) instead of quest ID?

**Comment by leatrix** [comment]
DoesQuestHaveRequirementsMet() is called from GOSSIP_SHOW so that it can determine whether to select a quest or not.  In BCC, the quest ID is not available at GOSSIP_SHOW.  In Shadowlands, the quest ID is available at GOSSIP_SHOW so Leatrix Plus for Shadowlands uses the quest ID.

**Comment by leatrix** [comment]
Try 2.5.47.alpha.2 for the Marks of Sargeras issue.
https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all

**Comment by leatrix** [comment]
Closing as no updates for 14 days.
