### ISSUE TITLE
[Feature Request] Hide error messages - Configurable Options (Yellow Quest Text/etc)

### ISSUE THREAD

**Issue by boktai1000** [leatrix/leatrix-plus-bcc#49]
I've encountered a number of times where something "Failed Succesfully" I'll just say that left me baffled - I'm personally too used to having quest objective completion text for example (Yellow Text - such as "Demon Broiled Soup 1/1") showing when succesful objectives are completed for quests/etc.

I'm not sure if they fall into the same catch-all bucket with the rest of the Red error messages, but if it at all would be possible to have a configurable cog/settings for this option to allow for selecting Yellow and Red messages and not catch those "Informationals" or "Warning" level yellow text items, but still filter out the noise like "Not enough rage" - that would be the perfect setup (for me at least!)

Thanks for taking the time to hear my suggestion - I understand if this is not possible due to how it's filtered with Blizzard related options - or maybe there is a more advanced way to whitelist/allow through certain objectives (not sure on this?) to allow for quests to show/etc

**Comment by leatrix** [comment]
'Hide error messages' ('Text') only blocks red error messages in the error frame.  It doesn't block yellow informational messages such as quest updates.  If you aren't seeing quest update messages, disable 'Hide error messages' and see if that fixes it.  

Other addons and macros can hide quest updates.

If you have the LTP minimap button enabled, you can CTRL/right-click it to toggle error messages without affecting the 'Hide error messages' setting.  You will see an alert message in the middle of the screen when error messages are toggled with the minimap button.
