### ISSUE TITLE
Druid shapeshift bar disappear 

### ISSUE THREAD

**Issue by Warlodude** [leatrix/leatrix-plus-bcc#51]
after logging in i noticed that the druid shapeshift bar for the forms have disappeared. iv tried disabling the add-on but it didnt work.

**Comment by leatrix** [comment]
Did you enable 'Hide stance bar' ('Frames')?

**Comment by Warlodude** [comment]
no. when add-on is disabled the bar re-appears. 
but when reactivated the bar goes missing again

**Comment by leatrix** [comment]
The only option that hides the stance bar (shapeshift bar) is 'Hide stance bar' ('Frames').  Disable all other addons and ensure 'Hide stance bar' is disabled.  Does the stance bar show now?

**Comment by Warlodude** [comment]
LMAO! YES FIXED... THANK YOU!
