### ISSUE TITLE
Release in PvP - Additional Options

### ISSUE THREAD

**Issue by boktai1000** [leatrix/leatrix-plus-bcc#52]
Hey there, I've been playing a lot of AV recently in BC Classic with the new changes for same faction BGs + the Alliance War Effort incentives going on.

One thing I've noticed in AV compared to the rest of the BGs, is that it's selective on when I'd like to release compared to the rest of the BGs. I was wondering if you could add toggles for each of the BGs to enable Auto Releasing?

An example situation is as follows: say you're in the enemy base, and die. You get sent multiple graveyards back up and possibly res immediately due to bad timing, when you may have wished to not release at all and try to look around for someone to res you and whisper them.

Since AV is sort of a PvPvE type BG, I think it acts a little differently compared to WSG/AB/EOTS where I would say 100% of the time I want to release immediately, but I've already had a handful of incidents where I wish I didn't. But I really appreciate the automation overall and it helps so much for the other BGs. The fact we can loot enemies and force them back, the mechanics lend itself to something of a more controlled option.

An additional idea I had, which honestly.. may not make sense at all, is an auto release after X seconds, with an override key like holding down shift or something. Say I die in AV, if I don't hold shift in maybe say 1 or 2 seconds after I die, just release me. But if I'm holding the override key, then let me release manual instead. I imagine you'd need to allow for something of a delay here since most people probably don't want to be holding the override key during their potential death. I dunno how I feel about this, but the idea came to me and I thought I'd at least bring it up to see if it resonated with you.

Anyways! Just wanted to run this by you and see your thoughts regarding it. Thanks for taking the time to read this enhancement idea and all of your assistance with tracking down things and questions I've had on the addon thus far. Cheers!

**Comment by leatrix** [comment]
In 2.5.59.alpha.6 or higher, you can exclude Alterac Valley, set a delay timer (between 200ms and 3000ms) and hold shift as the timer is ending to cancel automatic release.

https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all
