### ISSUE TITLE
Target of Target does not move with Target frame

### ISSUE THREAD

**Issue by Gasly313** [leatrix/leatrix-plus-bcc#53]
Does not seem to matter what I do, the Target of Target frame is just glued to the to UI so when I move all other frames closer to the centre of the screen, the Target of Target just sits up top left as if the Target frame was still above it.

Would love a fix for this. Thanks guys
![WoWScrnShot_080621_114322](https://user-images.githubusercontent.com/88519889/128443229-87b9d308-9b45-4d7d-9497-51c8cf80704a.jpg)
![WoWScrnShot_080621_114335](https://user-images.githubusercontent.com/88519889/128443233-48859fd7-e058-40c2-b020-bdab3c292f12.jpg)

**Comment by leatrix** [comment]
First thing's first: https://github.com/leatrix/leatrix-plus-bcc/issues/32.

**Comment by Gasly313** [comment]
> First thing's first: #32.

Should have said this - already done

**Comment by leatrix** [comment]
Show screenshot with all addons disabled.

The ToT frame is anchored to the Target frame by default.  Leatrix Plus doesn't change the anchor so you have installed another addon which has changed the anchor and caused the ToT frame to be positioned where it is.

Is the ToT frame incorrectly positioned on just one character or all characters?  Is it in the same place on all characters?

Try the following:

- Log out of the game completely.  Don't do this while you are logged into the game else it won't work.
- Navigate to Wow > _classic_ > WTF > Account > AccountID > Realm > CharacterName.  Do you see a file called layout-local.txt?  If you do, delete it.
- Log back into the game on the character you deleted layout-local.txt from, disable all addons and check the results.

**Comment by Gasly313** [comment]
That has fixed it. Thank you so much!
