### ISSUE TITLE
Autorepair function doesn't use guild funds

### ISSUE THREAD

**Issue by Krelln** [leatrix/leatrix-plus-bcc#56]
Hello there!
Addon's description says: "Repair your armor automatically (using guild funds if possible or character funds if not) when you talk to a repair merchant.", but it only uses character funds.
Function RepairAllItems() called without optional guildBankRepair argument(addon version 2.5.54) and there is no any checkouts about guild bank availability(I'm not sure, but I think it will be GetGuildBankWithdrawMoney/CanGuildBankRepair).

Hope it helps!
Thanks for your work!

**Comment by leatrix** [comment]
Guild bank support has been added to the latest alpha
https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all
