### ISSUE TITLE
Band of eternity auto turn in

### ISSUE THREAD

**Issue by whitestar87** [leatrix/leatrix-plus-bcc#59]
Please remove band of eternity auto turn in from 'automate quest' feature.  I just turned in for a caster ring as a hunter before i could even read the text

https://tbc.wowhead.com/quest=10463/sages-pledge
https://tbc.wowhead.com/quest=10462/champions-pledge
https://tbc.wowhead.com/quest=10460/defenders-pledge
https://tbc.wowhead.com/quest=10461/restorers-pledge

3 people in my guild are in the same boat, and since you cannot reach exalted with scale of sands we will not be able to get correct rings for probably more than 6 months.  Blizzard will not assist.  Pls fix ASAP!

**Comment by leatrix** [comment]
2.5.58.alpha.1 - 24th September 2021
- Quests from Soridormi and Arazmodu (The Scale of the Sands, Caverns of Time) will no longer be selected, accepted or turned-in automatically.

https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all

If you want me to exclude any NPCs in future from 'Automate quests', just let me know the NPC ID as well as the quest titles.  You can find the NPC ID by targeting the NPC and entering **/ltp id**.  Blizzard should really add a confirmation prompt for such important decisions as this.
