### ISSUE TITLE
TBC Classic bug

### ISSUE THREAD

**Issue by GregoryGH** [leatrix/leatrix-plus-bcc#6]
x [ADDON_ACTION_BLOCKED] AddOn 'Leatrix_Plus' tried to call the protected function 'GMSubmitBug()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GMSubmitBug'
[string "@Blizzard_PTRFeedback\Blizzard_PTRFeedback_Frames.lua"]:456: in function `SubmitBugReport'
[string "@Blizzard_PTRFeedback\Blizzard_PTRFeedback.lua"]:485: in function `func'
[string "@Blizzard_PTRFeedback\Blizzard_PTRFeedback.lua"]:373: in function `TriggerEvent'
[string "@Blizzard_PTRFeedback\Blizzard_PTRFeedback_Events.lua"]:21: in function `eventFunction'
[string "@Blizzard_PTRFeedback\Blizzard_PTRFeedback_Events.lua"]:46: in function <...Blizzard_PTRFeedback\Blizzard_PTRFeedback_Events.lua:42>

**Comment by leatrix** [comment]
It's caused by an issue with Blizzard's bug reporting system so just ignore it for now.  It's a harmless error that only affects the PTR and Beta realms (because those realms use the bug reporting system).  You won't see the error on live realms when the pre-patch lands on Tuesday/Wednesday.
