### ISSUE TITLE
Incorrect game version reported in curseforge client

### ISSUE THREAD

**Issue by MyTechnoHunter** [leatrix/leatrix-plus-bcc#60]
![image](https://user-images.githubusercontent.com/55214545/135323182-dd2ffd71-7ddf-426f-89ab-1295af3541bd.png)

as noted above, it still shows as game version 2.5.1

the website correctly says 2.5.2

**Comment by leatrix** [comment]
You're right.  This has been a problem for a long time with CurseForge App.  It was also a problem with Twitch App when CurseForge was part of Twitch.  It affects all Leatrix addons for every game but it also affects many other addons too (such as Raider.IO Mythic Plus and Raid progress and Mythic Dungeon Tools).  I submitted a ticket to CurseForge just in case something can be done but there isn't really anything I can do about it except wait for CurseForge to fix it.

**Comment by leatrix** [comment]
All Leatrix addons now use a third party packager to fix the CurseForge App issue. The addon version, game version, change log, etc, are now showing correctly in the app. If the latest updates don't show up in CurseForge App, close the app and launch it again.
