### ISSUE TITLE
Out of date changelog in curseforge

### ISSUE THREAD

**Issue by MyTechnoHunter** [leatrix/leatrix-plus-bcc#63]
tried to report on the curseforge page as this is related to that _not_ the addon itself that i know of.. 

when you view the changelog of the addon, this shows.

![image](https://user-images.githubusercontent.com/55214545/139192498-932dffcf-06eb-4903-ac8c-42f00e9d9f7d.png)

as you can see, this is NOT the latest changelog.. can you look into that please and thanks?

**Comment by leatrix** [comment]
All Leatrix addons now use a third party packager to fix the CurseForge App issue.  The addon version, game version, change log, etc, are now showing correctly in the app.  If the latest updates don't show up in CurseForge App, close the app and launch it again.
