### ISSUE TITLE
Feature Request - Region Crossing

### ISSUE THREAD

**Issue by RedYamash** [leatrix/leatrix-plus-bcc#67]
Hi, would it be possible to add a "highlighted path" or a marker between regions showing the crossing between regions? Something like a gate icon or a treasure map-like dotted path. The map artwork is terrible at showing those and discovering the world can be sometimes painstakingly difficult. Thanks for your work.

**Comment by leatrix** [comment]
Added to 2.5.70.alpha.4.  New setting in 'Show points of interest' called 'Show zone crossings'.  If enabled, zone crossings will be shown.  These are clickable arrows that indicate zone exit pathways.

https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all
