### ISSUE TITLE
auto quest turnin fails at last single sunfury signet

### ISSUE THREAD

**Issue by chorp-cpu** [leatrix/leatrix-plus-bcc#68]
ltp bcc 2.5.69
Magistrix Fyalenn in Shatt offers 2 quests
more sunfury signets (10 at a time)
single sunfury signet  (1 at a time)

if automate quests is enabled, and you have an amount say 4, it can auto turnin the first 3 then is unable to auto turnin the last one.

**Comment by leatrix** [comment]
Many thanks.  Should be fixed in 2.5.70.alpha.4 for BCC (as well as the latest Shadowlands alpha).

https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all

> 2.5.70.alpha.4 - 28th November 2021
> - Fixed a minor issue with 'Automate quests' ('Automation') which caused Mark of Sargeras and Sunfury Signet reputation turn-ins to not be automated if you only had one of either item in your bags.
