### ISSUE TITLE
minimap location is weird after recent Learix plus updates

### ISSUE THREAD

**Issue by SunnyJang38** [leatrix/leatrix-plus-bcc#69]
minimap location is weird after recent Learix plus updates

i use [basicminimap](https://www.curseforge.com/wow/addons/basic-minimap)

**Comment by techlx** [comment]
same here, i use default blz minimap ui

even untick "hide location information" but still location name on top of minimap is hidden

**Comment by jaktalf** [comment]
Unchecking "enhance minimap" in settings seems to move the map back where its supposed to be for me

**Comment by leatrix** [comment]
Install 9.1.26 (latest release).  You can move the minimap to anywhere you like and it won't affect the action bars or buff bars.
https://github.com/leatrix/leatrix-plus-classic/issues/26
https://github.com/leatrix/leatrix-plus/issues/61
Suggestion about zone text bar noted.

**Comment by SunnyJang38** [comment]
> Install the latest release. You can move the minimap to anywhere you like and it won't affect the action bars or buff bars. [leatrix/leatrix-plus-classic#26](https://github.com/leatrix/leatrix-plus-classic/issues/26) [leatrix/leatrix-plus#61](https://github.com/leatrix/leatrix-plus/issues/61) Suggestion about zone text bar noted.

it's occured by install leatrix plus 2.5.71-bcc
r u suggestion reinstall recent version, really?

**Comment by leatrix** [comment]
Ensure 2.5.71 is installed.
Open the configuration panel for 'Enhance minimap' ('Interface').
Ensure 'Unlock the minimap' is checked.
Now you can hold alt and drag the minimap anywhere you like.

**Comment by leatrix** [comment]
In the latest alpha, you can toggle the zone text bar once again using a setting in the configuration panel.

https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all

**Comment by leatrix** [comment]
Tested BMM with LTP 2.5.72 and it seems to work fine.  Ensure 'Unlock the minimap' is checked in LTP so you can drag the minimap by holding down alt.  Ensure 'Hide the zone text bar is checked' too since BMM has its own zone text.
