### ISSUE TITLE
Battlemaster Dialog Skip

### ISSUE THREAD

**Issue by shocker13** [leatrix/leatrix-plus-bcc#70]
Greetings. It would be nice to have an option to skip dialogs with battlemasters in TBC. There's an outdated WA for classic version that might be useful to begin with "https://wago.io/7iQ-sIq4g". Thank you for your work.

**Comment by leatrix** [comment]
Added to 2.5.73.alpha.3 for BCC and 1.14.13.alpha.3 for Classic Era/SoM.

> 2.5.73.alpha.3 - 7th December 2021
> - If 'Automate gossip' ('Automation') is enabled, battlemaster gossip will now be automatically selected and the battleground name will be shown at the top of the battlefield instance window.

https://www.curseforge.com/wow/addons/leatrix-plus-bcc/files/all
https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/all

**Comment by shocker13** [comment]
Amazing job, thanks!
