### ISSUE TITLE
Suggestion: Character Specific Options (Frames)

### ISSUE THREAD

**Issue by s4dio** [leatrix/leatrix-plus-bcc#75]
Hi,

It would be useful if there was an option for "apply to this character only" or similar.

When using LTP to move and manage frames, I prefer one position for DPS classes and another for tank classes. Currently, when swapping between 2 characters on the same account, the player frame and target frame positions will be synced across characters. 

Example:
I have my player and target frames aligned centrally on my paladin. However, on my hunter I want to have them closer to the top left of the main UI. There doesn't appear to be a way to have these options persist, meaning I have to rearrange the frames every time I swap between the characters.

NB: I can't add labels myself, so for ref. this is **not a bug report**.

**Comment by leatrix** [comment]
You posted in the right place.  GitHub call it Issues but you can use it for feedback too.

Leatrix addons don't use character profiles.  However, if you don't want to scale the player and target frames, you can do that with the default UI and the positions will be saved to your character.  The original intent when making 'Manage frames' was to have these positions saved account-wide so there would be no need to position them for every character.  If you don't want that and you don't want to change the player and target frame scale, just uncheck 'Manage frames' and use the default UI to save the frame positions.

**Comment by s4dio** [comment]
That's perfect and a great workaround. I'll try it out. Thanks!
