### ISSUE TITLE
newset update 2.5.81-bcc broke it all

### ISSUE THREAD

**Issue by knasen88** [leatrix/leatrix-plus-bcc#78]
Message: Error loading Interface\AddOns\Leatrix_Plus\Leatrix_Plus_Flight.lua
Time: Wed Dec 29 17:26:24 2021
Count: 3

**Comment by knasen88** [comment]
reinstalled and restarted client worked

**Comment by leatrix** [comment]
I wrote in the change log and added a login chat message advising that you need to restart your game client after installing this update for BCC.  Client restarts are required in BCC when an addon's file structure changes (they aren't required in Classic Era/SoM/Shadowlands).
