### ISSUE TITLE
Doesn't install via CurseForge

### ISSUE THREAD

**Issue by repsejnworb** [leatrix/leatrix-plus-bcc#8]
For some reason the addon doesn't install via CurseForge.
It gets listed inthe CurseForge app, but without a gameversion and not added to the AddOn-folder.

Unsure if something is maybe missing to honor w/e CurseForge needs to determine game version.

![image](https://user-images.githubusercontent.com/2539756/118943381-d90f1300-b953-11eb-8bc6-90e2ab045560.png)

**Comment by leatrix** [comment]
I can see all Leatrix addons listed in CurseForge App under Shadowlands, but not BCC.  And Wow Classic is not listed in the game version dropdown menu so I can't check for that.

Where are you seeing Leatrix Plus for BCC in CurseForge App?  If I search for 'Leatrix' under BCC, no results are shown.

I have submitted a ticket.

**Comment by repsejnworb** [comment]
> Where are you seeing Leatrix Plus for BCC in CurseForge App? If I search for 'Leatrix' under BCC, no results are shown.

I too didn't find it in the app, but with Google. 
So I installed "successfully" via https://www.curseforge.com/wow/addons/leatrix-plus-bcc and the "Install"-button, which then made it show up in the app under "My Addons" but not actually on disk.
(So as a workaround for now I just downloaded the zip).

> I have submitted a ticket.
👍 
I think "my work" here is done then :)

Thank you so much for developing and continuously updating your addons mate!

**Comment by leatrix** [comment]
If anyone is having problems finding Leatrix addons in CurseForge App, the best thing you can do is to submit a ticket to CurseForge explaining about the addons missing from the app.  You can do so here:
https://support.curseforge.com/

**Comment by brett1337** [comment]
my other addons automatically recognized that they needed to switch from classic to BCC, but leatrix didn't. if I install it from searching for it will I lose my settings?

**Comment by leatrix** [comment]
CurseForge App, by default , deletes addon settings files when you delete an addon (unless you told it not to in the app settings).  If you're worried about it, you can make a backup of your settings files (they are in Wow > _classic_ > WTF > Account > Account ID > SavedVariables and the files are Leatrix_Plus.lua and Leatrix.Plus.lua.bak.  Make a copy of those to be safe.  All the settings are in those files.  If you're using other Leatrix addons, the settings files will be there too.

After that, again if you want to be safe, manually delete the Leatrix_Plus folder from Wow > _classic_ > Interface > AddOns using Explorer and then use CurseForge App to install Leatrix Plus (remember to select BCC from the game dropdown menu).  Manually deleting the folder will ensure that your settings aren't lost just in case you have CurseForge App configured to delete addon settings when you use the app to delete an addon.

There was an issue preventing Leatrix addons for BCC from appearing in CurseForge App but it should all be fixed now.  You should see Leatrix addons in the app and get updates through the app too.
