### ISSUE TITLE
Southshore - SW flight timer longer than estimated

### ISSUE THREAD

**Issue by Remymanden** [leatrix/leatrix-plus-bcc#80]
roughly 10 sec

**Comment by leatrix** [comment]
Please install the latest alpha (or wait until tomorrow when it'll be released for everyone).  In the alpha, when you take a flight that has an incorrect or missing flight time (incorrect being more than a 5 second difference), you will see a window when you land.  The window will contain the flight information and it will already be highlighted for you so all you have to do is press CTRL/C to copy then paste it into a ticket here (or you can message leatrix on curseforge or send an email to flight@leatrix.com, whichever you prefer).  I'll update the addon when I have the flight details and you will never see that window again for that flight.  But I need the flight details that are shown to you when you land.  If people report the flight details for incorrect or missing flights, we can make the setting work reliably with every flight.

**Comment by leatrix** [comment]
I did actually look at Southshore to Stormwind Alliance BCC and the time was spot on so it may be that it had already been fixed in a more recent alpha than you had installed.  Thanks for reporting it either way.
