### ISSUE TITLE
FLIGHT TIMES BCC - REPORT THEM HERE

### ISSUE THREAD

**Issue by leatrix** [leatrix/leatrix-plus-bcc#87]
Please paste your incorrect or missing flight time reports for BCC in this ticket so that I can add them to the addon.  I will put a thumbs up to your post when I have added the flight time.

Keep Leatrix Plus up-to-date otherwise you might be posting flight times that already exist in the latest release of the addon.  You can use [CurseForge Desktop App](https://download.curseforge.com/) to keep Leatrix Plus up-to-date.

**Comment by Epsynus** [comment]
Updated to the latest version and already got a new time for ya!
Thanks again for your hard work!

Flight details (BCC): Shattrath (0.44:0.67) to Altar of Sha'tar (0.81:0.77) (Horde) took 215 seconds (2 hop).

["0.44:0.67:0.51:0.73:0.66:0.77"] = 215, -- Shattrath, Stonebreaker Hold, Shadowmoon Village

This flight's actual time of 215 seconds does not match the saved flight time of 133 seconds.

**Comment by Epsynus** [comment]
another:
Flight details (BCC): Altar of Sha'tar (0.81:0.77) to Shadowmoon Village (0.66:0.77) (Horde) took 67 seconds (1 hop).

["0.81:0.77:0.66:0.77"] = 67, -- Altar of Sha'tar, Shadowmoon Village

This flight does not exist in the database.

**Comment by Shanoga** [comment]
Flight details (BCC): Altar of Sha'tar (0.81:0.77) to Honor Hold (0.65:0.58) (Alliance) took 276 seconds (2 hop).

["0.81:0.77:0.55:0.77:0.65:0.58"] = 276, -- Altar of Sha'tar, Allerian Stronghold, Honor Hold

This flight does not exist in the database.

**Comment by Shanoga** [comment]
Flight details (BCC): Altar of Sha'tar (0.81:0.77) to Shattrath (0.44:0.67) (Alliance) took 254 seconds (2 hop).

["0.81:0.77:0.55:0.77:0.44:0.67"] = 254, -- Altar of Sha'tar, Allerian Stronghold, Shattrath

This flight does not exist in the database.

**Comment by philcgilbert** [comment]
Flight details (BCC): Thelsamar (0.53:0.61) to Sentinel Hill (0.39:0.80) (Alliance) took 340 seconds (3 hop).

["0.53:0.61:0.47:0.59:0.41:0.73:0.39:0.80"] = 340, -- Thelsamar, Ironforge, Stormwind, Sentinel Hill

This flight does not exist in the database.

**Comment by Epsynus** [comment]
Flight details (BCC): Area 52 (0.58:0.27) to Altar of Sha'tar (0.81:0.77) (Horde) took 437 seconds (5 hop).

["0.58:0.27:0.49:0.36:0.44:0.51:0.44:0.67:0.51:0.73:0.66:0.77:0.81:0.77"] = 437, -- Area 52, Mok'Nathal Village, Swamprat Post, Shattrath, Stonebreaker Hold, Shadowmoon Village, Altar of Sha'tar

This flight does not exist in the database.

**Comment by jhenry82** [comment]
Flight details (BCC): Darkshire (0.47:0.79) to Southshore (0.44:0.45) (Alliance) took 548 seconds (6 hop).

["0.47:0.79:0.50:0.75:0.52:0.72:0.47:0.65:0.47:0.59:0.50:0.42:0.44:0.45"] = 548, -- Darkshire, Lakeshire, Morgan's Vigil, Thorium Point, Ironforge, Aerie Peak, Southshore

This flight does not exist in the database.

**Comment by Iowerth** [comment]
Flight details (BCC): Шаттрат (0.44:0.67) to Святилище Звезд (0.78:0.85) (Horde) took 198 seconds (2 hop).

["0.44:0.67:0.51:0.73:0.66:0.77:0.78:0.85"] = 198, -- Шаттрат, Форт Камнеломов, Деревня Призрачной Луны, Святилище Звезд

This flight does not exist in the database.

**Comment by ltpgithub007** [comment]
Flight details (BCC): Southshore (0.44:0.45) to Stormwind (0.41:0.73) (Alliance) took 370 seconds (3 hop).

["0.44:0.45:0.45:0.56:0.47:0.59:0.41:0.73"] = 370, -- Southshore, Menethil Harbor, Ironforge, Stormwind

This flight does not exist in the database.

**Comment by ltpgithub007** [comment]
Flight details (BCC): Stormwind (0.41:0.73) to Thelsamar (0.53:0.61) (Alliance) took 274 seconds (2 hop).

["0.41:0.73:0.47:0.59:0.53:0.61"] = 274, -- Stormwind, Ironforge, Thelsamar

This flight does not exist in the database.

**Comment by axlroden** [comment]
Flight details (BCC): Sentinel Hill (0.39:0.80) to Ironforge (0.47:0.59) (Alliance) took 288 seconds (2 hop).

["0.39:0.80:0.41:0.73:0.47:0.59"] = 288, -- Sentinel Hill, Stormwind, Ironforge

This flight's actual time of 288 seconds does not match the saved flight time of 331 seconds.

**Comment by Shanoga** [comment]
Flight details (BCC): Orebor Harborage (0.27:0.44) to The Stormspire (0.63:0.18) (Alliance) took 253 seconds (4 hop).

["0.27:0.44:0.38:0.50:0.42:0.37:0.58:0.27:0.63:0.18"] = 253, -- Orebor Harborage, Telredor, Toshley's Station, Area 52, The Stormspire

This flight does not exist in the database.

**Comment by philcgilbert** [comment]
Flight details (BCC): Thelsamar (0.53:0.61) to Stormwind (0.41:0.73) (Alliance) took 277 seconds (2 hop).

["0.53:0.61:0.47:0.59:0.41:0.73"] = 277, -- Thelsamar, Ironforge, Stormwind

This flight does not exist in the database.

**Comment by godsyn** [comment]
Flight details (BCC): Stormwind (0.41:0.73) to Southshore (0.44:0.45) (Alliance) took 497 seconds (3 hop).

["0.41:0.73:0.47:0.59:0.50:0.42:0.44:0.45"] = 497, -- Stormwind, Ironforge, Aerie Peak, Southshore

This flight does not exist in the database.

**Comment by burak185** [comment]
Flight details (BCC): Southshore (0.44:0.45) to Nethergarde Keep (0.55:0.81) (Alliance) took 517 seconds (5 hop).

["0.44:0.45:0.45:0.56:0.47:0.59:0.47:0.65:0.41:0.73:0.55:0.81"] = 517, -- Southshore, Menethil Harbor, Ironforge, Thorium Point, Stormwind, Nethergarde Keep

This flight does not exist in the database.

**Comment by Dyspareunia** [comment]
Flight details (BCC): Stormwind (0.41:0.73) to Chillwind Camp (0.48:0.39) (Alliance) took 484 seconds (3 hop).

["0.41:0.73:0.47:0.59:0.50:0.42:0.48:0.39"] = 484, -- Stormwind, Ironforge, Aerie Peak, Chillwind Camp

This flight does not exist in the database.

**Comment by jbeercow** [comment]
Flight details: Rut'theran Village (0.42:0.16) to Thalanaar (0.48:0.70) (Alliance) took 846 seconds.  This flight's actual time of 846 seconds does not match the saved flight time of 711 seconds.

**Comment by leatrix** [comment]
@jbeercow I can't add this as I need the full flight string.  Please update Leatrix Plus and submit reports when they appear.  The latest version includes the full flight string in the flight report.

**Comment by Sarkal** [comment]
Flight details (BCC): Orgrimmar (0.63:0.44) to Moonglade (0.54:0.21) (Horde) took 371 seconds (4 hop).

["0.63:0.44:0.55:0.42:0.50:0.35:0.46:0.30:0.54:0.21"] = 371, -- Orgrimmar, Splintertree Post, Emerald Sanctuary, Bloodvenom Post, Moonglade

This flight does not exist in the database.

Thanks a lot for your work !

**Comment by ltpgithub007** [comment]
Flight details (BCC): Booty Bay (0.41:0.93) to Refuge Pointe (0.51:0.47) (Alliance) took 562 seconds (3 hop).

["0.41:0.93:0.41:0.73:0.47:0.59:0.51:0.47"] = 562, -- Booty Bay, Stormwind, Ironforge, Refuge Pointe

This flight does not exist in the database.

**Comment by ltpgithub007** [comment]
Flight details (BCC): Refuge Pointe (0.51:0.47) to Booty Bay (0.41:0.93) (Alliance) took 570 seconds (4 hop).

["0.51:0.47:0.45:0.56:0.47:0.59:0.41:0.73:0.41:0.93"] = 570, -- Refuge Pointe, Menethil Harbor, Ironforge, Stormwind, Booty Bay

This flight does not exist in the database.

**Comment by burak185** [comment]
Flight details (BCC): Auberdine (0.43:0.25) to Everlook (0.65:0.23) (Alliance) took 279 seconds (2 hop).

["0.43:0.25:0.53:0.26:0.65:0.23"] = 279, -- Auberdine, Talonbranch Glade, Everlook

This flight does not exist in the database.

**Comment by Meatslabb** [comment]
Flight details (BCC): Area 52 (0.58:0.27) to Shattrath (0.44:0.67) (Horde) took 311 seconds (3 hop).

["0.58:0.27:0.38:0.32:0.44:0.51:0.44:0.67"] = 311, -- Area 52, Thunderlord Stronghold, Swamprat Post, Shattrath

This flight does not exist in the database.

**Comment by burak185** [comment]
Flight details (BCC): Darkshire (0.47:0.79) to Menethil Harbor (0.45:0.56) (Alliance) took 360 seconds (3 hop).

["0.47:0.79:0.41:0.73:0.47:0.59:0.45:0.56"] = 360, -- Darkshire, Stormwind, Ironforge, Menethil Harbor

This flight does not exist in the database.

**Comment by godsyn** [comment]
Flight details (BCC): Stormwind (0.41:0.73) to Aerie Peak (0.50:0.42) (Alliance) took 446 seconds (4 hop).

["0.41:0.73:0.47:0.65:0.53:0.61:0.51:0.47:0.50:0.42"] = 446, -- Stormwind, Thorium Point, Thelsamar, Refuge Pointe, Aerie Peak

This flight's actual time of 446 seconds does not match the saved flight time of 508 seconds.

**Comment by jhenry82** [comment]
Flight details (BCC): Telaar (0.27:0.74) to Evergrove (0.42:0.28) (Alliance) took 269 seconds (3 hop).

["0.27:0.74:0.38:0.50:0.32:0.34:0.42:0.28"] = 269, -- Telaar, Telredor, Sylvanaar, Evergrove

This flight does not exist in the database.

**Comment by godsyn** [comment]
Flight details (BCC): Nethergarde Keep (0.55:0.81) to Chillwind Camp (0.48:0.39) (Alliance) took 570 seconds (4 hop).

["0.55:0.81:0.52:0.72:0.47:0.65:0.47:0.59:0.48:0.39"] = 570, -- Nethergarde Keep, Morgan's Vigil, Thorium Point, Ironforge, Chillwind Camp

This flight's actual time of 570 seconds does not match the saved flight time of 631 seconds.

**Comment by godsyn** [comment]
Flight details (BCC): Nethergarde Keep (0.55:0.81) to Light's Hope Chapel (0.61:0.35) (Alliance) took 664 seconds (4 hop).

["0.55:0.81:0.52:0.72:0.47:0.65:0.47:0.59:0.61:0.35"] = 664, -- Nethergarde Keep, Morgan's Vigil, Thorium Point, Ironforge, Light's Hope Chapel

This flight's actual time of 664 seconds does not match the saved flight time of 687 seconds.

**Comment by Epsynus** [comment]
Flight details (BCC): Gadgetzan (0.61:0.80) to Shadowprey Village (0.32:0.58) (Horde) took 463 seconds (2 hop).

["0.61:0.80:0.45:0.56:0.32:0.58"] = 463, -- Gadgetzan, Thunder Bluff, Shadowprey Village

This flight does not exist in the database.

**Comment by alexey-detr** [comment]
Flight details (BCC): Алтарь Ша'тар (0.81:0.77) to Траллмар (0.65:0.50) (Horde) took 263 seconds (2 hop).

["0.81:0.77:0.51:0.73:0.65:0.50"] = 263, -- Алтарь Ша'тар, Форт Камнеломов, Траллмар

This flight does not exist in the database.

**Comment by Grumpycow** [comment]
Flight details (BCC): Moonglade (0.54:0.21) to Orgrimmar (0.63:0.44) (Horde) took 384 seconds (2 hop).

["0.54:0.21:0.64:0.23:0.63:0.44"] = 384, -- Moonglade, Everlook, Orgrimmar

This flight does not exist in the database.

**Comment by Gunzelb** [comment]
Flight details (BCC): Darkshire (0.47:0.79) to Southshore (0.44:0.45) (Alliance) took 439 seconds (5 hop).

["0.47:0.79:0.50:0.75:0.52:0.72:0.47:0.65:0.47:0.59:0.44:0.45"] = 439, -- Darkshire, Lakeshire, Morgan's Vigil, Thorium Point, Ironforge, Southshore

This flight's actual time of 439 seconds does not match the saved flight time of 517 seconds.

**Comment by philcgilbert** [comment]
Flight details (BCC): Menethil Harbor (0.45:0.56) to Lakeshire (0.50:0.75) (Alliance) took 358 seconds (3 hop).

["0.45:0.56:0.47:0.59:0.41:0.73:0.50:0.75"] = 358, -- Menethil Harbor, Ironforge, Stormwind, Lakeshire

This flight does not exist in the database.

**Comment by jhenry82** [comment]
Flight details (BCC): Ironforge (0.47:0.59) to Aerie Peak (0.50:0.42) (Alliance) took 299 seconds (1 hop).

["0.47:0.59:0.50:0.42"] = 299, -- Ironforge, Aerie Peak

This flight's actual time of 299 seconds does not match the saved flight time of 240 seconds.

**Comment by MetalMaxim** [comment]
Flight details (BCC): Shadowmoon Village (0.66:0.77) to Altar of Sha'tar (0.81:0.77) (Horde) took 85 seconds (1 hop).

["0.66:0.77:0.81:0.77"] = 85, -- Shadowmoon Village, Altar of Sha'tar

This flight does not exist in the database.

**Comment by Xikun201** [comment]
Flight details (BCC): Der ewige Hain (0.42:0.28) to Altar der Sha'tar (0.81:0.77) (Horde) took 452 seconds (5 hop).

["0.42:0.28:0.38:0.32:0.44:0.51:0.44:0.67:0.51:0.73:0.66:0.77:0.81:0.77"] = 452, -- Der ewige Hain, Donnerfeste, Sumpfrattenposten, Shattrath, Steinbrecherfeste, Schattenmond, Altar der Sha'tar

This flight does not exist in the database.

**Comment by Offroads** [comment]
Flight details (BCC): Stonebreaker Hold (0.51:0.73) to Altar of Sha'tar (0.81:0.77) (Horde) took 149 seconds (1 hop).

["0.51:0.73:0.66:0.77:0.81:0.77"] = 149, -- Stonebreaker Hold, Shadowmoon Village, Altar of Sha'tar

This flight does not exist in the database.

**Comment by MetalMaxim** [comment]
Flight details (BCC): The Sepulcher (0.37:0.41) to Revantusk Village (0.59:0.45) (Horde) took 255 seconds (2 hop).

["0.37:0.41:0.46:0.43:0.59:0.45"] = 255, -- The Sepulcher, Tarren Mill, Revantusk Village

This flight's actual time of 255 seconds does not match the saved flight time of 289 seconds.

**Comment by elysix** [comment]
Flight details (BCC): Booty Bay (0.41:0.93) to Sentinel Hill (0.39:0.80) (Alliance) took 148 seconds (1 hop).

["0.41:0.93:0.39:0.80"] = 148, -- Booty Bay, Sentinel Hill

This flight's actual time of 148 seconds does not match the saved flight time of 181 seconds.

**Comment by Epsynus** [comment]
Flight details (BCC): Altar of Sha'tar (0.81:0.77) to Area 52 (0.58:0.27) (Horde) took 398 seconds (5 hop).

["0.81:0.77:0.51:0.73:0.44:0.67:0.44:0.51:0.49:0.36:0.58:0.27"] = 398, -- Altar of Sha'tar, Stonebreaker Hold, Shattrath, Swamprat Post, Mok'Nathal Village, Area 52

This flight does not exist in the database.

**Comment by Blumberg1337** [comment]
Flight details (BCC): Beutebucht (0.41:0.93) to Nistgipfel (0.50:0.42) (Alliance) took 633 seconds (4 hop).

["0.41:0.93:0.41:0.73:0.47:0.59:0.51:0.47:0.50:0.42"] = 633, -- Beutebucht, Sturmwind, Eisenschmiede, Die Zuflucht, Nistgipfel

This flight does not exist in the database.

**Comment by burak185** [comment]
Flight details (BCC): Darkshire (0.47:0.79) to Chillwind Camp (0.48:0.39) (Alliance) took 503 seconds (3 hop).

["0.47:0.79:0.41:0.73:0.47:0.59:0.48:0.39"] = 503, -- Darkshire, Stormwind, Ironforge, Chillwind Camp

This flight does not exist in the database.

**Comment by Epsynus** [comment]
Flight details (BCC): Area 52 (0.58:0.27) to Shadowmoon Village (0.66:0.77) (Horde) took 443 seconds (5 hop).

["0.58:0.27:0.38:0.32:0.44:0.51:0.44:0.67:0.51:0.73:0.66:0.77"] = 443, -- Area 52, Thunderlord Stronghold, Swamprat Post, Shattrath, Stonebreaker Hold, Shadowmoon Village

This flight does not exist in the database.

**Comment by Epsynus** [comment]
Flight details (BCC): Area 52 (0.58:0.27) to Thrallmar (0.65:0.50) (Horde) took 359 seconds (4 hop).

["0.58:0.27:0.38:0.32:0.44:0.51:0.54:0.57:0.65:0.50"] = 359, -- Area 52, Thunderlord Stronghold, Swamprat Post, Falcon Watch, Thrallmar

This flight does not exist in the database.

**Comment by Epsynus** [comment]
Flight details (BCC): Stonebreaker Hold (0.51:0.73) to The Stormspire (0.63:0.18) (Horde) took 385 seconds (5 hop).

["0.51:0.73:0.44:0.67:0.44:0.51:0.38:0.32:0.58:0.27:0.63:0.18"] = 385, -- Stonebreaker Hold, Shattrath, Swamprat Post, Thunderlord Stronghold, Area 52, The Stormspire

This flight does not exist in the database.

**Comment by Kazrarg** [comment]
Flight details (BCC): Camp Mojache (0.44:0.69) to Marshal's Refuge (0.50:0.76) (Horde) took 301 seconds (3 hop).

["0.44:0.69:0.55:0.73:0.61:0.80:0.50:0.76"] = 301, -- Camp Mojache, Freewind Post, Gadgetzan, Marshal's Refuge

This flight does not exist in the database.

**Comment by burak185** [comment]
Flight details (BCC): Sentinel Hill (0.39:0.80) to Darkshire (0.47:0.79) (Alliance) took 97 seconds (1 hop).

["0.39:0.80:0.47:0.79"] = 97, -- Sentinel Hill, Darkshire

This flight's actual time of 97 seconds does not match the saved flight time of 108 seconds.

**Comment by zopa34** [comment]
Flight details (BCC): Freewind Post (0.55:0.73) to Ratchet (0.61:0.55) (Horde) took 243 seconds (2 hop).

["0.55:0.73:0.56:0.53:0.61:0.55"] = 243, -- Freewind Post, Crossroads, Ratchet

This flight does not exist in the database.

**Comment by Blumberg1337** [comment]
Flight details (BCC): Booty Bay (0.41:0.93) to Nethergarde Keep (0.55:0.81) (Alliance) took 258 seconds (2 hop).

["0.41:0.93:0.47:0.79:0.55:0.81"] = 258, -- Booty Bay, Darkshire, Nethergarde Keep

This flight does not exist in the database.

**Comment by blueyez8889** [comment]
Flight details (BCC): Sentinel Hill (0.39:0.80) to Darkshire (0.47:0.79) (Alliance) took 97 seconds (1 hop).

["0.39:0.80:0.47:0.79"] = 97, -- Sentinel Hill, Darkshire

This flight's actual time of 97 seconds does not match the saved flight time of 108 seconds.

**Comment by dbrtomusa** [comment]
Flight details (BCC): Stonebreaker Hold (0.51:0.73) to Cosmowrench (0.72:0.28) (Horde) took 403 seconds (5 hop).

["0.51:0.73:0.44:0.67:0.44:0.51:0.38:0.32:0.58:0.27:0.72:0.28"] = 403, -- Stonebreaker Hold, Shattrath, Swamprat Post, Thunderlord Stronghold, Area 52, Cosmowrench

This flight does not exist in the database.

**Comment by jhenry82** [comment]
Flight details (BCC): Astranaar (0.46:0.40) to Talonbranch Glade (0.53:0.26) (Alliance) took 338 seconds (2 hop).

["0.46:0.40:0.43:0.25:0.53:0.26"] = 338, -- Astranaar, Auberdine, Talonbranch Glade

This flight does not exist in the database.

**Comment by Iowerth** [comment]
Детали полета (BCC): Святилище Звезд (0.78:0.85) до Оплот Громоборцев (0.38:0.32) (Horde) взять 371 секунд (4 hop).

["0.78:0.85:0.51:0.73:0.44:0.67:0.44:0.51:0.38:0.32"] = 371, -- Святилище Звезд, Форт Камнеломов, Шаттрат, Застава Болотной Крысы, Оплот Громоборцев

Этот маршрут не существует в базе данных.

**Comment by Ev3ryb0dy** [comment]
Flight details (BCC): Moonglade (0.54:0.21) to Orgrimmar (0.63:0.44) (Horde) took 371 seconds (2 hop).

["0.54:0.21:0.46:0.30:0.63:0.44"] = 371, -- Moonglade, Bloodvenom Post, Orgrimmar

This flight does not exist in the database.
