### ISSUE TITLE
Leatrix Plus BCC won't install

### ISSUE THREAD

**Issue by chongo420** [leatrix/leatrix-plus-bcc#9]
Add-on wont show up in game despite files being in the BCC add-on folder

**Comment by leatrix** [comment]
Close BCC game client completely and relaunch.  If you still have problems, please attach screenshots of your addons folder and your Leatrix_Plus folder.

**Comment by leatrix** [comment]
Sadly, the awesome Shadowlands feature which allows you to install addons without client restarts was not added to BCC.  Client restarts are still required after installing addons in BCC (just as with Classic Era).
