### ISSUE TITLE
/ltp does not work now

### ISSUE THREAD

**Issue by Git-Bill-Hub** [leatrix/leatrix-plus-bcc#94]
I updated a few hours ago and I don't think LTP is loading at all. My auto repair and junk sell stopped working, so I tried to go into /ltp and that didn't work.

**Comment by leatrix** [comment]
If /ltp doesn't work, something is stopping LTP from loading correctly.  That's probably another addon.  Disable all other addons and try again.  Did you update LTP regularly?  When did you update before the last time?

**Comment by Git-Bill-Hub** [comment]
I updated a few hours ago.

I just disabled all addons except LTP and its still not loading.  Its the only addon with a check mark next to it, but its not working.

**Comment by leatrix** [comment]
There is one thing.. which locale are you using?  enUS or another one?  If you're not sure, enter this in game:

/run print(GetLocale())

**Comment by Git-Bill-Hub** [comment]
enUS

**Comment by leatrix** [comment]
Restart your Wow client.  I don't know when the last time you updated was but there was an update a few weeks ago that required a client restart.  If you didn't update in a few weeks (before the last one), then that's probably it.

**Comment by leatrix** [comment]
I'm assuming that fixed it?  If not, [this](https://github.com/leatrix/leatrix-plus-bcc/issues/95#issuecomment-1014360237) could be relevant.

**Comment by Git-Bill-Hub** [comment]
I did not, even rebooted before raid.

However, the update that got pushed out today, does seem to have fixed it.
So it looks like all good now.

**Comment by leatrix** [comment]
CurseForge didn't package the addon files correctly as explained [here](https://github.com/leatrix/leatrix-plus-bcc/issues/95#issuecomment-1014360237).  This does happen sometimes but it's very rare.
