### ISSUE TITLE
Getting Lua Error

### ISSUE THREAD

**Issue by Gogo1951** [leatrix/leatrix-plus-bcc#95]
Message: Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:9213: attempt to index field 'MaxCameraZoom' (a nil value)
Time: Sun Jan 16 21:40:34 2022
Count: 3
Stack: Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:9213: attempt to index field 'MaxCameraZoom' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua"]:9213: in function `?'
[string "@Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua"]:10594: in function <Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:10220>

Locals: errMsg = "Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:9213: attempt to index field 'MaxCameraZoom' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:296
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by Gogo1951** [comment]
Message: Interface\AddOns\Leatrix_Plus\Leatrix_Plus_Locale.lua:17: unexpected symbol near '<'
Time: Sun Jan 16 21:57:09 2022
Count: 1
Stack: Interface\AddOns\Leatrix_Plus\Leatrix_Plus_Locale.lua:17: unexpected symbol near '<'
[string "=[C]"]: ?

Locals:

**Comment by leatrix** [comment]
Sorry about that.  This is an issue with 2.5.86.alpha.13 and it's caused by CurseForge packager.  It seems a server was down when CurseForge tried to package the addon.  This can happen but it's very rare.  I released a new alpha 2.5.86.alpha.14 so CurseForge can package it again.  It should be fine.  Thanks for reporting it.
