### ISSUE TITLE
Enhance Professions broke with the new patch

### ISSUE THREAD

**Issue by Epsynus** [leatrix/leatrix-plus-bcc#98]
Running version 2.5.86.

This is how the profession window looks after the latest patch:
[https://imgur.com/a/2VbarIv](https://imgur.com/a/2VbarIv)

It goes away and displays normally if I disable the Enhance Profession option in LTP - Interface.

**Comment by leatrix** [comment]
Sorry about that.  It seems that Blizzard changed the layout of the professions frame a bit.  Should be fixed in 2.5.87.  Thanks for reporting the bug.

**Comment by Epsynus** [comment]
Can confirm it is now fixed, thanks for the quick response! 👍
