### ISSUE TITLE
Feature request : use cast bar for flight timer

### ISSUE THREAD

**Issue by godsyn** [leatrix/leatrix-plus-bcc#99]
Allow an option to use the built-in cast timer bars in flight.
The current bar may not conform to other's UI choices.
Using the built in cast bars allows users to manipulate the bars with whatever addon they please (default built-in, quartz, Classic Castbars, etc.).

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-plus-bcc/issues/92
